### ISSUE TITLE
Option to not cache the list of .gz files

### ISSUE THREAD

**Issue by danyg** [code42day/connect-gzip-static#13]
Hi, I would like to be able to turn off the behaviour of creation existent .gz files in the root, and be able serve generated .gz files after the initialization of the server.

**Comment by pirxpilot** [comment]
Strangely enough checking if the `.gz` files exists before serving it is **exactly** what this middleware was doing in its initial incarnation - see [version 0.2.1][1]
The initial scan of the file system was added in [version 0.3.0] since as the Readme implies `connect-gzip-static` is meant to be used with the build process that generates compressed files.

Any particular reason why you need to dynamically check for newly added compressed files?

[1]: https://github.com/code42day/connect-gzip-static/blob/0.2.1/lib/gzip-static.js

**Comment by danyg** [comment]
well yes, in my project (cucumber-statistics)[https://github.com/danyg/cucumber-statistics] cucumber.json files are loaded to the server, this files contains images (screenshots) encoded as base64, so what I wanted is to store those images in .gz files (only) I don't care about old browser or mobiles phones, the whole app is not intended to be accessed in that way, so the server is already running when this files are created, is the same server that serves those files the one that is creating it. So another option would be to trigger a re-indexation after that creation of those files, that option would have done more complex to implement in both side of the code, that is why I add this feature in this way.

**Comment by pirxpilot** [comment]
Makes sense. I am not against adding that again, if it can be done cleanly. In the meantime do try installing 0.2.1 - chances are it's going to work for you.
